bigro/matcheam

- build.gradle
> spring-boot-starter-web入れました

- build.gradle
- src/main/java/matcheam/Enemy.java
- src/main/java/matcheam/Game.java
- src/main/java/matcheam/GameService.java
- src/main/java/matcheam/Identifier.java
- src/main/java/matcheam/Place.java
- src/test/java/matcheam/GameServiceTest.java
> 試合登録サービス作成

- build.gradle
- src/main/java/matcheam/MatchRegisterController.java
- src/main/java/matcheam/MatchService.java
- src/main/resources/templates/match/register.html
- src/main/resources/templates/match/result.html
> 登録画面と登録完了画面を表示させるようにした

- src/main/java/matcheam/EntryUser.java
- src/main/java/matcheam/EntryUserService.java
- src/main/java/matcheam/Match.java
- src/main/java/matcheam/MatchController.java
- src/main/java/matcheam/MatchService.java
- src/main/java/matcheam/Matching.java
- src/main/java/matcheam/MatchingService.java
- src/test/java/matcheam/EntryUserServiceTest.java
- src/test/java/matcheam/MatchServiceTest.java
- src/test/java/matcheam/MatchingServiceTest.java
> 募集に応募できること

- .gitignore
- src/main/java/matcheam/MatchController.java
- src/main/java/matcheam/MatchingService.java
- src/main/resources/templates/match/detail.html
- src/main/resources/templates/match/search.html
- src/test/java/matcheam/MatchingServiceTest.java
connect to #22 
検索→詳細→募集までの骨組み作成した
> Matchingable

- src/main/java/matcheam/ApplicationController.java
- src/main/resources/templates/index.html
> 素朴なトップページ作った

- src/main/resources/templates/match/register.html
> 最大人数登録できるように

- src/main/java/matcheam/common/Converter.java
- src/main/java/matcheam/common/SystemContext.java
- src/main/java/matcheam/common/exception/SystemException.java
- src/main/java/matcheam/jooq/generate/tables/records/MatchRecord.java
- src/main/java/matcheam/match/Match.java
- src/main/java/matcheam/match/MatchController.java
- src/main/java/matcheam/match/MatchRepository.java
- src/main/java/matcheam/match/MatchService.java
- src/main/java/matcheam/person/Person.java
- src/main/resources/templates/match/search.html
- src/test/java/matcheam/MatchServiceSearchTest.java
- src/test/java/matcheam/MatchServiceTest.java
- src/test/java/matcheam/MatchingServiceTest.java
- src/test/java/matcheam/common/ConverterTest.java
> データアクセス導入#49

- src/main/java/matcheam/match/MatchService.java
- src/main/resources/templates/match/search.html
> 一覧の開始日を表示する

- src/main/java/matcheam/jooq/generate/Matcheam.java
- src/main/java/matcheam/jooq/generate/Sequences.java
- src/main/java/matcheam/jooq/generate/tables/Match.java
- src/main/java/matcheam/match/Identifier.java
- src/main/java/matcheam/match/MatchController.java
- src/main/java/matcheam/matching/Matching.java
- src/main/java/matcheam/matching/MatchingService.java
- src/main/java/matcheam/person/PersonService.java
- src/main/resources/templates/match/detail.html
- src/test/java/matcheam/EntryUserServiceTest.java
- src/test/java/matcheam/MatchingServiceTest.java
> リファクタリングをしました

- src/main/java/matcheam/match/MatchService.java
- src/main/resources/templates/match/search.html
> 一覧画面に開始時間を表示

- src/main/resources/templates/match/detail.html
> 詳細画面の日付フォーマットを変更した

- src/main/resources/templates/match/detail.html
> 詳細画面に開始時間を表示

- src/main/resources/templates/match/search.html
> 募集一覧の行ごとのリンクを無くした

- src/main/java/matcheam/match/MatchRepository.java
- src/main/java/matcheam/match/MatchService.java
> jooqをmatchserviceから追い出した

- build.gradle
- src/main/java/matcheam/match/MatchRepository.java
- src/main/java/matcheam/match/MatchService.java
- src/test/java/matcheam/MatchServiceSearchTest.java
- src/test/java/matcheam/match/MatchRepositoryTest.java
- src/test/java/matcheam/support/TestContext.java
> レベル検索をDBアクセスして検索するようにした

- src/main/java/matcheam/entry/Entry.java
- src/main/java/matcheam/entry/EntryRepository.java
- src/main/java/matcheam/entry/EntryUser.java
- src/main/java/matcheam/match/Match.java
- src/main/java/matcheam/match/MatchController.java
- src/main/java/matcheam/match/MatchRepository.java
- src/main/resources/db/migration/V1__Create_match_table.sql
- src/main/resources/db/migration/V2__Add_match.sql
- src/main/resources/templates/match/detail.html
- src/test/java/matcheam/entry/EntryRepositoryTest.java
- src/test/java/matcheam/match/MatchRepositoryRegisterTest.java
- src/test/java/matcheam/match/MatchRepositorySearchTest.java
- src/test/java/matcheam/support/MatchBuilder.java
- src/test/java/matcheam/support/TestDataSource.java
- src/test/java/matcheam/support/TestSupport.java
> EntryUser周りのリファクタリング

- src/test/java/matcheam/AbstractTest.java
- src/test/java/matcheam/entry/EntryRepositoryTest.java
- src/test/java/matcheam/match/MatchRepositoryRegisterTest.java
- src/test/java/matcheam/match/MatchRepositorySearchTest.java
> TestDataSourceの初期化をbeforeClassに移動した

- src/main/resources/templates/index.html
- src/main/resources/templates/match/detail.html
- src/main/resources/templates/match/register.html
- src/main/resources/templates/match/result.html
- src/main/resources/templates/match/search.html
> Toppage look and feel#92

- coworking_place.txt
- src/main/resources/templates/index.html
- src/main/resources/templates/match/detail.html
- src/main/resources/templates/match/menu.html
- src/main/resources/templates/match/pageHeader.html
- src/main/resources/templates/match/register.html
- src/main/resources/templates/match/result.html
- src/main/resources/templates/match/search.html
> Make gui structured#101

- src/main/resources/templates/match/register.html
> 登録画面をかっこよくした（デザイン）

- src/main/resources/templates/index.html
- src/main/resources/templates/match/detail.html
- src/main/resources/templates/match/menu.html
- src/main/resources/templates/match/register.html
- src/main/resources/templates/match/result.html
- src/main/resources/templates/match/search.html
> htmlタグを見直した（かっこよくした）

- src/main/resources/templates/match/search.html
> 検索ボタンにスタイルを当てた

- src/main/java/matcheam/match/MatchController.java
- src/main/resources/templates/match/detail.html
> 募集詳細の応募に必須チェックを入れた

- src/main/java/matcheam/match/Match.java
- src/main/java/matcheam/match/MatchController.java
- src/main/resources/templates/match/register.html
> Required check for entry#117

- src/main/resources/templates/match/search.html
> いちらんのID消した

- src/main/java/matcheam/match/Match.java
- src/main/resources/templates/match/detail.html
- src/main/resources/templates/match/search.html
> 試合応募人数を表示できるようにした

- build.gradle
> jooqのバージョンアップ

- build.gradle
- src/main/java/matcheam/match/Match.java
- src/main/java/matcheam/match/MatchRepository.java
- src/main/resources/db/migration/V1__Create_match_table.sql
- src/main/resources/templates/match/detail.html
- src/main/resources/templates/match/register.html
- src/test/java/matcheam/match/MatchRepositoryRegisterTest.java
- src/test/java/matcheam/support/TestSupport.java
> Addremarks#119
